#!/bin/bash

scriptDir=$(dirname $0)

/bin/bash $scriptDir/../privateScripts/generateVersionDescriptors.sh

# add the version descriptors to the git index
git add $scriptDir/../config/versionDescriptors