# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages: # List of stages for jobs, and their order of execution
    - build
    - deploy

compiling: # This job runs in the build stage, which runs first.
    image: gradle:8-jdk21
    stage: build
    script:
        - gradle buildFatJar --no-daemon

build_docker:
    stage: deploy
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    image: ubuntu:latest
    tags:
        - docker_local
    script:
        - apt-get update && apt-get install -y curl
        - curl -fsSL https://get.docker.com | sh # Install Docker
        # https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files
        - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash # Install the secure files tool
        - cp .secure_files/production.json ./config/ # Copy the production.json file to the config folder uploaded to GitLab before
        - cp .secure_files/db.env ./docker/ # Copy the db.env file to the config folder uploaded to GitLab before
        - cp .secure_files/AuthKey_58V5WA3RLA.p8 ./config/ # Copy the Apple Notification Key file to the config folder uploaded to GitLab before
        - ./run-backend.sh
    except:
        - tags # Do not run this job on tags
