version: "3.1"

services:
    db:
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: expoll
        hostname: db
        volumes:
            - mysqlDB:/var/lib/mysql
        container_name: database
    api:
        build:
            context: ../
            dockerfile: ./server/dockerfile
        restart: unless-stopped
        ports:
            - "6060:6060"
        volumes:
            - ./config:/expoll/api_server/config
        environment:
            - NODE_ENV=production
        container_name: apiServer
        hostname: api
        depends_on:
            - "db"
        links:
            - "db"
    nginx:
        build:
            context: ../
            dockerfile: ./server/nginx/dockerfile
        restart: unless-stopped
        ports:
            - "80:80"
        container_name: nginx
        depends_on:
            - "api"
            - "db"
        hostname: nginx
        links:
            - "api"

volumes:
    mysqlDB:
