version: "3.1"

services:
    db:
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: expoll
        env_file:
            - db.env
        hostname: db
        volumes:
            - expoll_db:/var/lib/mysql
        container_name: expoll_database
        networks:
            - expoll_net
    api:
        build:
            context: ../../
            dockerfile: ./server/Dockerfile
        restart: unless-stopped
        environment:
            - NODE_ENV=production
        container_name: expoll_apiServer
        hostname: api
        depends_on:
            - "db"
        links:
            - "db"
        networks:
            - expoll_net
    caddy:
        build:
            context: ../../
            dockerfile: ./server/caddy/Dockerfile
        restart: unless-stopped
        container_name: expoll_caddy
        depends_on:
            - "api"
            - "db"
        hostname: nginx
        links:
            - "api"
        networks:
            - expoll_net
            - out
#        ports:
#            - "80:80"

volumes:
    expoll_db:
networks:
    expoll_net:
        name: expoll_net
        attachable: true
    out:
        name: out
        external: true
# used ports internally: 3306, 6060
# used ports "externally": 80
