version: "3.1"

services:
    db:
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: expoll
        env_file:
            - /opt/expoll/server/docker/db.env
        hostname: db
        volumes:
            - mysqlDB:/var/lib/mysql
        container_name: expoll_database
        networks:
            - expoll_net
    api:
        build:
            context: ../../
            dockerfile: ./server/dockerfile
        restart: unless-stopped
        ports:
            - "6060:6060"
        volumes:
            - ../config:/expoll/api_server/config
        environment:
            - NODE_ENV=production
        container_name: expoll_apiServer
        hostname: api
        depends_on:
            - "db"
        links:
            - "db"
        networks:
            - expoll_net
    nginx:
        build:
            context: ../../
            dockerfile: ./server/nginx/dockerfile
        restart: unless-stopped
        ports:
            - "81:80"
        container_name: expoll_nginx
        depends_on:
            - "api"
            - "db"
        hostname: nginx
        links:
            - "api"
        networks:
            - expoll_net

volumes:
    mysqlDB:
networks:
    expoll_net:
        name: expoll_net
        attachable: true
