version: "3.1"

services:
    db:
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: expoll
        volumes:
            - mysqlDB:/var/lib/mysql
        container_name: expoll_database

volumes:
    mysqlDB:
