
from node as compiler
WORKDIR /expoll/lib
COPY ./lib .
RUN npm install
RUN npm run build

WORKDIR /expoll/frontend_server
COPY ./client .

RUN npm install
RUN npm run build


FROM nginx
COPY ./server/nginx/default.conf /etc/nginx/conf.d/default.conf
#COPY ./backend-not-found.html /var/www/html/backend-not-found.html
COPY ./server/nginx/includes/ /etc/nginx/includes/
#COPY ./ssl/ /etc/ssl/certs/nginx/
COPY --from=0 /expoll/frontend_server/dist /www/data

EXPOSE 80