---
- name: Deploy docker containers on server
  hosts: all
  become: true
  become_method: sudo

  vars:
      expoll_directories:
          - src: ../../server/
            dest: server
          #- src: ../../lib/
          #  dest: lib
          - src: ../../client/
            dest: client
      install_dir: "/opt/expoll/"
      date: "{{ lookup('pipe', 'date +%Y_%m_%d-%H_%M') }}"

  vars_files:
      - vars.yml

  pre_tasks:
      - name: Create docker mysql backup
        shell: sudo docker exec -i expoll_database mysqldump -uroot -ppassword expoll > /tmp/expoll_db.sql
      - name: Copy docker mysql backup to local
        fetch:
            src: /tmp/expoll_db.sql
            dest: ../backups/expoll_db_{{ date }}.sql
            flat: yes
            fail_on_missing: yes
      - name: Push repositories to server
        synchronize:
            src: "{{ item.src }}"
            dest: "{{  install_dir }}{{ item.dest }}"
            recursive: true
            owner: false
            group: false
            mode: push
            delete: true
            rsync_opts:
                - "--exclude=.git"
                - "--exclude=**/node_modules"
                - "--exclude=compiled"
                - "--exclude=dist"
                - "--exclude=*.tsbuildinfo"
            private_key: "~/.ssh/mt32"
        with_items: "{{ expoll_directories }}"

  tasks:
      - name: copy nginx config file
        copy:
            src: ./expoll.nginx.conf
            dest: /etc/nginx/sites-enabled/expoll
      - name: Create docker containers and start servers
        script:
            chdir: "{{  install_dir }}server/"
            cmd: "../run-full-server.sh"
